### ISSUE TITLE
emf-maven-plugin maven dependency for Apache Axis1

### ISSUE THREAD

**Issue by robertlazarski** [veithen/emf-maven-plugin#3]
The Apache Axis 1.x file axis-model/pom.xml, references this project but it isn't resolving correctly. 

<plugin>
                <groupId>com.github.veithen.cosmos</groupId>
                <artifactId>emf-maven-plugin</artifactId>
                <version>0.1-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate-sources</goal>
                        </goals>
                        <configuration>
                            <genmodel>model/axis.genmodel</genmodel>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

[ERROR] Plugin com.github.veithen.cosmos:emf-maven-plugin:0.1-SNAPSHOT or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.github.veithen.cosmos:emf-maven-plugin:jar:0.1-SNAPSHOT: Failure to find com.github.veithen:parent:pom:21-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced

**Comment by veithen** [comment]
I've created a release and updated Axis.
