### ISSUE TITLE
Allow specify default and property-name for the genmodel

### ISSUE THREAD

**Issue by Peter-Rader** [veithen/emf-maven-plugin#364]
In order to use the [Convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration) principle, please implement a default-value for the genmodel-argument. And please create a parameter-name to avoid big xml-configuration-node in the pom.xml.

**Comment by Peter-Rader** [comment]
And outputDirectory please.

**Comment by veithen** [comment]
What do you mean by "create a parameter-name"?

**Comment by Peter-Rader** [comment]
I have created a pull-request in order to explain the problem. Please have a look, thanks for your attention.
